import express from 'express';
const router  = express.Router();

import cityRoutes from './cityRoutes.js';
import appointmentRoutes from './appointmentRoutes.js';
import categoryRoutes from './categoryRoutes.js';
import blogRoutes from './blogRoutes.js';
import commentRoutes from './commentRoutes.js';
import cmsRoutes from './cmsRoutes.js';
import inquiryRoutes from './inquiryRoutes.js';
import mediaRoutes from './mediaRoutes.js';
import offerRoutes from './offerRoutes.js';
import ourClinicRoutes from './ourClinicRoutes.js';
import ourFactRoutes from './ourFactRoutes.js';
import redirectionRoutes from './redirectionRoutes.js';
import serviceRoutes from './serviceRoutes.js';
import testimonialRoutes from './testimonialRoutes.js';
import videoGalleryRoutes from './videoGalleryRoutes.js';
import galleryRoutes from './galleryRoutes.js';
import categoryfaqroute from './categoryfaqroute.js';
import userRoute from './userRoutes.js';
router.use('/city', cityRoutes);
router.use('/appointment', appointmentRoutes);
router.use('/category', categoryRoutes);
router.use('/blog', blogRoutes);
router.use('/comment', commentRoutes);
router.use('/cms', cmsRoutes);
router.use('/inquiry', inquiryRoutes);
router.use('/media', mediaRoutes);
router.use('/offer', offerRoutes);
router.use('/clinic', ourClinicRoutes);
router.use('/fact', ourFactRoutes);
router.use('/redirection', redirectionRoutes);
router.use('/service', serviceRoutes);
router.use('/testimonial', testimonialRoutes);
router.use('/video', videoGalleryRoutes);
router.use('/image', galleryRoutes);
router.use('/faq', categoryfaqroute);
router.use('/user', userRoute)
export default router;
